insert into pittura (id, tipo, materialeSupporto) values (3015, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3020, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'olio su tela', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'altro', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'altro', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3006, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3006, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'altro', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3010, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3029, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'affresco', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3006, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3017, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3021, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3029, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3010, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'olio su tela', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'acquerello', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3029, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'olio su tela', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3020, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3029, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'acquerello', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3006, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3010, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3029, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3011, 'tempera', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3023, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'acquerello', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3011, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3012, 'altro', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3011, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3020, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'acquerello', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'affresco', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3010, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3023, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3020, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'olio su tela', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'altro', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3029, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3010, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3012, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3023, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3012, 'altro', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3012, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3020, 'acquerello', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'olio su tela', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'altro', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3023, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3021, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3023, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3021, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3011, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3025, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3010, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'altro', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3009, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'acquerello', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3020, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'acquerello', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3012, 'olio su tela', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'affresco', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3006, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3020, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3006, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3011, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3011, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3028, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3021, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3027, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'affresco', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3007, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'tempera', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3029, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3017, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3004, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3019, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3011, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (3023, 'olio su tela', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3016, 'acquerello', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3026, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3018, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3017, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3023, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3015, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3013, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (3017, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (3022, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3012, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3008, 'tempera', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (3024, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (3012, 'acquerello', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'olio su tela', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (3005, 'affresco', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (3014, 'acquerello', 'Glass');
