INSERT INTO Stile (Nome) VALUES
('Realismo'),
('Impressionismo'),
('Espressionismo'),
('Cubismo'),
('Surrealismo'),
('Futurismo'),
('Dadaismo'),
('Barocco'),
('Rococò'),
('Rinascimento'),
('Neoclassicismo'),
('Romanticismo'),
('Minimalismo'),
('Pop Art'),
('Art Nouveau'),
('Art Déco'),
('Astrattismo'),
('Simbolismo'),
('Fauvismo'),
('Costruttivismo'),
('Suprematismo'),
('Op Art'),
('Arte concettuale'),
('Street Art'),
('Arte digitale'),
('Vaporwave'),
('Cyberpunk'),
('Steampunk'),
('Low Poly'),
('Pixel Art'),
('Ukiyo-e'),
('Chiaroscuro'),
('Gotico'),
('Brutalismo'),
('Bauhaus'),
('Arte Naïf'),
('Hyperrealismo'),
('Matte Painting'),
('Anime'),
('Manga'),
('Ghibli-style'),
('Noir'),
('Synthwave'),
('Retrofuturismo'),
('Biomeccanico'),
('Glitch Art'),
('Graffiti'),
('Arte psichedelica'),
('Medievale'),
('Bizantino'),
('Preraffaellita'),
('Tonalismo'),
('Divisionismo'),
('Puntinismo'),
('Constructivist Poster'),
('Flat Design'),
('Line Art'),
('Cartoon'),
('Cel Shading'),
('Acquerello'),
('Pittura a olio'),
('Carboncino'),
('Ink Wash'),
('Collage'),
('Paper Cut'),
('Arte tribale'),
('Arte celtica'),
('Arte nordica'),
('Fantasy Art'),
('Dark Fantasy'),
('Sci-Fi Art');