insert into pittura (id, tipo, materialeSupporto) values (6006, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6007, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6008, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6009, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6010, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6011, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6012, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6013, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6014, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6015, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6016, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6017, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6018, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6019, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6020, 'olio su tela', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6021, 'altro', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6022, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6023, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6024, 'altro', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6025, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6026, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6027, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6028, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6029, 'altro', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6030, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6031, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6032, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6033, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6034, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6035, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6036, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6037, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6038, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6039, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6040, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6041, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6042, 'affresco', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6043, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6044, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6045, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6046, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6047, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6048, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6049, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6050, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6051, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6052, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6053, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6054, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6055, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6056, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6057, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6058, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6059, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6060, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6061, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6062, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6063, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6064, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6065, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6066, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6067, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6068, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6069, 'olio su tela', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6070, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6071, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6072, 'acquerello', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6073, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6074, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6075, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6076, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6077, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6078, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6079, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6080, 'olio su tela', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6081, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6082, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6083, 'tempera', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6084, 'acquerello', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6085, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6086, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6087, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6088, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6089, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6090, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6091, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6092, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6093, 'tempera', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6094, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6095, 'acquerello', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6096, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6097, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6098, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6099, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6100, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6101, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6102, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6103, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6104, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6105, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6106, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6107, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6108, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6109, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6110, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6111, 'altro', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6112, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6113, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6114, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6115, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6116, 'acquerello', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6117, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6118, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6119, 'affresco', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6120, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6121, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6122, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6123, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6124, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6125, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6126, 'olio su tela', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6127, 'altro', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6128, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6129, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6130, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6131, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6132, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6133, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6134, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6135, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6136, 'acquerello', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6137, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6138, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6139, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6140, 'altro', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6141, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6142, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6143, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6144, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6145, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6146, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6147, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6148, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6149, 'acquerello', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6150, 'olio su tela', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6151, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6152, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6153, 'affresco', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6154, 'altro', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6155, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6156, 'altro', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6157, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6158, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6159, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6160, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6161, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6162, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6163, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6164, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6165, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6166, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6167, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6168, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6169, 'altro', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6170, 'acquerello', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6171, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6172, 'altro', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6173, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6174, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6175, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6176, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6177, 'affresco', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6178, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6179, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6180, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6181, 'altro', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6182, 'acquerello', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6183, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6184, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6185, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6186, 'tempera', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6187, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6188, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6189, 'acquerello', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6190, 'tempera', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6191, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6192, 'acquerello', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6193, 'olio su tela', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6194, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6195, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6196, 'affresco', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6197, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6198, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6199, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6200, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6201, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6202, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6203, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6204, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6205, 'affresco', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6206, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6207, 'altro', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6208, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6209, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6210, 'olio su tela', 'Plastic');
insert into pittura (id, tipo, materialeSupporto) values (6211, 'affresco', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6212, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6213, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6214, 'acquerello', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6215, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6216, 'olio su tela', 'Steel');
insert into pittura (id, tipo, materialeSupporto) values (6217, 'affresco', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6218, 'olio su tela', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6219, 'affresco', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6220, 'tempera', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6221, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6222, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6223, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6224, 'olio su tela', 'Aluminum');
insert into pittura (id, tipo, materialeSupporto) values (6225, 'tempera', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6226, 'olio su tela', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6227, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6228, 'affresco', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6229, 'acquerello', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6230, 'tempera', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6231, 'tempera', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6232, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6233, 'olio su tela', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6234, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6235, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6236, 'tempera', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6237, 'altro', 'Brass');
insert into pittura (id, tipo, materialeSupporto) values (6238, 'olio su tela', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6239, 'acquerello', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6240, 'olio su tela', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6241, 'acquerello', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6242, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6243, 'altro', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6244, 'affresco', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6245, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6246, 'olio su tela', 'Vinyl');
insert into pittura (id, tipo, materialeSupporto) values (6247, 'tempera', 'Rubber');
insert into pittura (id, tipo, materialeSupporto) values (6248, 'altro', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6249, 'tempera', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6250, 'tempera', 'Granite');
insert into pittura (id, tipo, materialeSupporto) values (6251, 'altro', 'Wood');
insert into pittura (id, tipo, materialeSupporto) values (6252, 'acquerello', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6253, 'olio su tela', 'Stone');
insert into pittura (id, tipo, materialeSupporto) values (6254, 'affresco', 'Plexiglass');
insert into pittura (id, tipo, materialeSupporto) values (6255, 'acquerello', 'Glass');
insert into pittura (id, tipo, materialeSupporto) values (6256, 'olio su tela', 'Wood');