insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6076, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6071, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6249, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6048, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6020, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6091, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6054, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6007, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6134, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6044, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6064, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6034, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6134, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6033, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6118, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6098, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6256, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6173, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6216, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6172, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6116, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6238, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6115, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6094, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6177, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6052, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6255, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6037, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6089, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6038, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6248, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6047, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6058, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6120, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6039, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6218, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6035, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6189, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6030, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6196, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6244, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6247, 'acquerello', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6047, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6241, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6062, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6103, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6108, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6252, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6130, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6082, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6256, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6049, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6046, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6106, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6225, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6148, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6113, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6044, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6062, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6232, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6175, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6132, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6164, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6200, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6226, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6218, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6065, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6024, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6096, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6244, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6090, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6070, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6231, 'acquerello', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6139, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6031, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6041, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6215, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6245, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6221, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6236, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6044, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6014, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6015, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6107, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6132, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6167, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6095, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6076, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6168, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6203, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6209, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6063, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6016, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6120, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6231, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6125, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6017, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6112, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6066, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6077, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6241, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6159, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6133, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6065, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6065, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6053, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6238, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6026, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6131, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6122, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6234, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6164, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6134, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6155, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6161, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6117, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6080, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6077, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6134, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6136, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6188, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6117, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6176, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6140, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6012, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6063, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6210, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6058, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6210, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6032, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6128, 'acquerello', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6009, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6162, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6050, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6069, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6132, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6024, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6042, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6172, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6212, 'olio su tela', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6192, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6212, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6151, 'acquerello', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6239, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6246, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6249, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6160, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6027, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6016, 'acquerello', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6089, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6163, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6196, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6007, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6177, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6080, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6043, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6021, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6035, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6028, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6147, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6010, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6242, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6126, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6188, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6237, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6237, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6241, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6078, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6043, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6053, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6175, 'olio su tela', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6138, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6149, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6093, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6117, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6160, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6092, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6137, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6033, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6010, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6227, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6008, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6128, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6086, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6149, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6087, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6206, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6082, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6193, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6188, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6130, 'acquerello', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6068, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6137, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6213, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6057, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6070, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6221, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6109, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6113, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6101, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6059, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6119, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6249, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6248, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6066, 'acquerello', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6230, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6249, 'tempera', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6067, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6091, 'altro', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6066, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6176, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6248, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6066, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6067, 'acquerello', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6174, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6094, 'olio su tela', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6209, 'olio su tela', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6212, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6224, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6130, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6113, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6186, 'olio su tela', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6160, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6035, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6007, 'tempera', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6107, 'altro', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6214, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6108, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6022, 'affresco', 'legno');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6060, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6088, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6227, 'olio su tela', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6088, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6007, 'tempera', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6020, 'altro', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6089, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6028, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6061, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6140, 'altro', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6056, 'olio su tela', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6042, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6247, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6178, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6157, 'affresco', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6234, 'affresco', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6251, 'acquerello', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6119, 'olio su tela', 'tela');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6256, 'affresco', 'altro');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6036, 'tempera', 'carta');
insert into MOCK_DATA (ID, tipo, materialeSupporto) values (6150, 'acquerello', 'tela');
